# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Be awesome today
header-img: img/home-bg.jpg
email: trongthien18@gmail.com
copyright_name: Thien Le
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://trongthien18.github.io" # the base hostname & protocol for your site
twitter_username: trongthienle
github_username:  trongthien18
facebook_username:  trongthien.le
email_username:     trongthien18@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 5